openapi: 3.0.3
tags:
  - name: GetSingleFoo
    description: Get a single foo
  - name: Foo
    description: All foo operations
paths:
  /foo/{id}:
    get:
      security:
        - OAuth2:
            - read
      summary: Returns a single foo
      operationId: getFoo
      description: Find and returns a single Foo
      tags:
        - GetSingleFoo
        - Foo
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the foo to retrieve
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: One single Food
          content:
            application/json:
              schema:
                $ref: "./GetFooResponse.yaml"
        '404':
          description: Could not find any foo with given ID
          content:
            application/json:
              schema:
                $ref: "../../common/EmptyResponse.yaml"
        default:
          description: In all other cases an error is thrown
          content:
            application/json:
              schema:
                $ref: "../../common/RestError.yaml"
